import { usePageTitle } from '@/hooks/usePageTitle';
import { Link } from 'react-router-dom';
import { PageHeader } from '@/components/PageHeader';

const H = ({ children }: { children: string }) => <h2 className="text-base font-extrabold mt-6 mb-1.5 text-ink-100">{children}</h2>;

export default function TermsPage() {
  usePageTitle('Terms');
  return (
    <div className="max-w-2xl mx-auto pb-10">
      <PageHeader title="Terms of Use" subtitle="Plain language, no tricks. Last updated July 2026." />
      <div className="text-sm text-ink-200 leading-relaxed">
        <H>What VinaX is</H>
        <p>
          VinaX is a free music player for Indian and international music. It streams songs, artwork and lyrics from
          independent third-party public catalogs. VinaX does not host, own or sell any music, and displays titles,
          artists and film credits exactly as the catalog provides them.
        </p>
        <H>Free means free</H>
        <p>
          There are no subscriptions, no premium tiers, no in-app purchases and no advertising — and no plans for
          any. If you ever see VinaX asking for money, it isn&rsquo;t VinaX.
        </p>
        <H>No accounts</H>
        <p>
          You don&rsquo;t create an account, so there are no credentials to protect and nothing to ban. Your name,
          favorites, history and taste profile live only on your device — see the{' '}
          <Link to="/privacy" className="text-ember-400 hover:underline">Privacy page</Link> for exactly what that means.
        </p>
        <H>Availability</H>
        <p>
          Catalog sources can be briefly unavailable or remove content without notice. The app fails over between
          sources automatically, but no track&rsquo;s availability is guaranteed.
        </p>
        <H>AI features</H>
        <p>
          The AI DJ, home shelves, lyric explanations and VinaX AI chat are generated by AI models. They can be wrong,
          incomplete or oddly confident. Music picks are suggestions, chat answers are not professional advice, and
          nothing the AI writes should be treated as fact without checking.
        </p>
        <H>Fair use of the service</H>
        <p>
          Don&rsquo;t abuse the service: no scraping at scale, no attacking the infrastructure, no using Listen
          Together or the feedback form to harass people, and no attempting to re-sell access to something that is
          free. We may block abusive clients to protect everyone else.
        </p>
        <H>Rights holders</H>
        <p>
          If content should not be available, tell us via the{' '}
          <Link to="/dmca" className="text-ember-400 hover:underline">Copyright &amp; takedowns page</Link>. Verified
          requests are honored by removing the content from search, playback and recommendations across all clients.
        </p>
        <H>Changes and endings</H>
        <p>
          Features may change, improve or be retired at any time — the in-app changelog documents every release. If
          VinaX ever had to shut down, your data would not be lost: it&rsquo;s already on your device, and Settings →
          Your Data exports everything.
        </p>
        <H>No warranty</H>
        <p>
          VinaX is provided &ldquo;as is&rdquo;, without warranty of any kind. To the maximum extent permitted by law,
          VinaX and its maker are not liable for damages arising from use of the service. Use it in line with the laws
          of your region.
        </p>
        <p className="mt-6 text-ink-400">
          Questions? <Link to="/contact" className="text-ember-400 hover:underline">Contact us</Link>.
        </p>
      </div>
    </div>
  );
}
